mandatoryAccounts:
  - name: Management
    description: >-
      The management (primary) account. Do not change the name field for this
      mandatory account. Note, the account name key does not need to match the
      AWS account name.
    email: dearie+lza@fastmail.com
    organizationalUnit: Root
  - name: LogArchive
    description: >-
      The log archive account. Do not change the name field for this mandatory
      account. Note, the account name key does not need to match the AWS account
      name.
    email: deare+lza_logging@fastmail.com
    organizationalUnit: Security
  - name: Audit
    description: >-
      The security audit account (also referred to as the audit account). Do not
      change the name field for this mandatory account. Note, the account name
      key does not need to match the AWS account name.
    email: dearie+lza_audit@fastmail.com
    organizationalUnit: Security
workloadAccounts:
  - name: LogArchiveGC # referred to as LogArchive in the GovCloud account-config.yaml
    description: The log archive account for GovCloud.
    email: dearie+lza_logging_gc@fastmail.com
    # this OU has all GovCloud accounts.
    # OU was created from Control Tower
    # in organization-config.yaml this OU was added.
    organizationalUnit: GovCloud
    # enableGovCloud is a one-time non-reversible option
    # which only works with creation of new accounts
    enableGovCloud: false
  - name: AuditGC # referred to as Audit in the GovCloud account-config.yaml
    description: The security audit account (also referred to as the audit account) for GovCloud.
    email: dearie+lza_audit_gc@fastmail.com
    organizationalUnit: GovCloud
    enableGovCloud: false
  # - name: SharedServicesGC # referred to as SharedServices in the GovCloud account-config.yaml
  #   description: Shared services account for GovCloud.
  #   email: dearie+lza_services_gc
  #   organizationalUnit: GovCloud
  #   enableGovCloud: true
  # - name: NetworkGC # referred to as Network in the GovCloud account-config.yaml
  #   description: Network account for GovCloud.
  #   email: <govCloud-network-email@example.com> <----- UPDATE EMAIL ADDRESS
  #   organizationalUnit: GovCloud
  #   enableGovCloud: true
